### ISSUE TITLE
Problem trying to build vdb_to_numpy: vdb_pybind.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python23throw_error_already_setEv

### ISSUE THREAD

**Issue by amwfarid** [PRBonn/vdb_to_numpy#1]
Hi! I've been trying to run [make_it_dense](https://github.com/PRBonn/make_it_dense), but I stumbled upon this problem related to `vdb_to_numpy`. There seems to be a problem building the library; even though no errors occur during `pip install .` or alternatively `cmake`, in which both approaches lead to the undefined symbol error as shown below:

```
from vdb_to_numpy import vdb_to_triangle_mesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/farid/projects/make_it_dense/venv/lib/python3.8/site-packages/vdb_to_numpy/__init__.py", line 1, in <module>
    from .grid_wrappers import LeafNodeGrid
  File "/home/farid/projects/make_it_dense/venv/lib/python3.8/site-packages/vdb_to_numpy/grid_wrappers/__init__.py", line 1, in <module>
    from .blend_grids import blend_grids, normalize_grid
  File "/home/farid/projects/make_it_dense/venv/lib/python3.8/site-packages/vdb_to_numpy/grid_wrappers/blend_grids.py", line 3, in <module>
    from ..pybind import vdb_pybind
ImportError: /home/farid/projects/make_it_dense/venv/lib/python3.8/site-packages/vdb_to_numpy/pybind/vdb_pybind.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python23throw_error_already_setEv
```

It seems to be related to Boost. Although I tried installing the complete boost libraries through `apt install *boost*` (similar to this [issue](https://github.com/rdkit/rdkit/issues/2131)), I still get the same error. Am I missing something here?

My environment is:
- Ubuntu 20.04
- Python 3.8 (venv)
- Boost 1.71
- OpenVDB (using this [fork](https://github.com/nachovizzo/openvdb))

Thank you in advance!

**Comment by amwfarid** [comment]
I ended up redoing the environment setup again and got it to work! Looks like I had some conflicts with a previously installed boost 1.70. Will close this!
